server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo01
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  thymeleaf:
    suffix: .html
    prefix: classpath:templates/
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
